#include "view/menu/config/impresoras.hpp"

ViewImpresoras::ViewImpresoras(/* args */) : XML("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                                                 "<interface>"
                                                 "<requires lib=\"gtk\" version=\"4.0\"/>"
                                                 "<object class=\"GtkBox\" id=\"boxConfigImpresora\">"
                                                 "<property name=\"spacing\">10</property>"
                                                 "<property name=\"homogeneous\">true</property>"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<property name=\"orientation\">1</property>"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"margin-bottom\">20</property>"
                                                 "<property name=\"label\">Impresoras</property>"
                                                 "<style>"
                                                 "<class name=\"title-1\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"margin-bottom\">10</property>"
                                                 "<property name=\"label\">Seleccione la impresora a predeterminar para las operaciones.</property>"
                                                 "<style>"
                                                 "<class name=\"dim-label\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkScrolledWindow\">"
                                                 "<child>"
                                                 "<object class=\"GtkListBox\" id=\"listBoxPrint\">"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\" id=\"listBoxRowPrint\">"
                                                 "<property name=\"activatable\">false</property>"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\">"
                                                 "<property name=\"label\">Impresoras no encontradas</property>"
                                                 "<style>"
                                                 "<class name=\"title-2\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<style>"
                                                 "<class name=\"rich-list\"/>"
                                                 "<class name=\"boxed-list\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<property name=\"orientation\">1</property>"
                                                 "<property name=\"vexpand\">true</property>"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"margin-bottom\">20</property>"
                                                 "<property name=\"label\">Propiedades</property>"
                                                 "<style>"
                                                 "<class name=\"title-1\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkNotebook\" id=\"ntbookPropiedades\">"
                                                 "<property name=\"vexpand\">true</property>"
                                                 "<child>"
                                                 "<object class=\"GtkScrolledWindow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<property name=\"margin-bottom\">30</property>"
                                                 "<property name=\"margin-end\">10</property>"
                                                 "<property name=\"margin-start\">10</property>"
                                                 "<property name=\"orientation\">1</property>"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\">"
                                                 "<property name=\"label\">Activar</property>"
                                                 "<property name=\"margin-bottom\">10</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "<style>"
                                                 "<class name=\"title-2\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBox\" id=\"listBoxPage1\">"
                                                 "<property name=\"selection-mode\">0</property>"
                                                 "<property name=\"margin-bottom\">30</property>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblActivar1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">Activar Impresión</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkSwitch\" id=\"switchImpresion\">"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<style>"
                                                 "<class name=\"rich-list\"/>"
                                                 "<class name=\"boxed-list\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\">"
                                                 "<property name=\"label\">Visualización</property>"
                                                 "<property name=\"margin-bottom\">10</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "<style>"
                                                 "<class name=\"title-2\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBox\" id=\"listBoxVisualizacion1\">"
                                                 "<property name=\"selection-mode\">0</property>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblMensaje1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">Mensaje de Agradecimiento</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkCheckButton\" id=\"checkConfig1\">"
                                                 "<property name=\"active\">true</property>"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"margin-end\">10</property>"
                                                 "<property name=\"margin-start\">10</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblFecha1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">Fecha</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkCheckButton\" id=\"checkConfig2\">"
                                                 "<property name=\"active\">true</property>"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"margin-end\">10</property>"
                                                 "<property name=\"margin-start\">10</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblDireccion1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">Direccion</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkCheckButton\" id=\"checkConfig3\">"
                                                 "<property name=\"active\">true</property>"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"margin-end\">10</property>"
                                                 "<property name=\"margin-start\">10</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblRFC1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">RFC</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkCheckButton\" id=\"checkConfig4\">"
                                                 "<property name=\"active\">true</property>"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"margin-end\">10</property>"
                                                 "<property name=\"margin-start\">10</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblVendedor1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">Vendedor</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkCheckButton\" id=\"checkConfig5\">"
                                                 "<property name=\"active\">true</property>"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"margin-end\">10</property>"
                                                 "<property name=\"margin-start\">10</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblContacto1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">Contacto</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkCheckButton\" id=\"checkConfig6\">"
                                                 "<property name=\"active\">true</property>"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"margin-end\">10</property>"
                                                 "<property name=\"margin-start\">10</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<style>"
                                                 "<class name=\"rich-list\"/>"
                                                 "<class name=\"boxed-list\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\">"
                                                 "<property name=\"label\">Test</property>"
                                                 "<property name=\"margin-bottom\">10</property>"
                                                 "<property name=\"margin-top\">30</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "<style>"
                                                 "<class name=\"title-2\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkListBox\" id=\"listBoxTest1\">"
                                                 "<property name=\"selection-mode\">0</property>"
                                                 "<child>"
                                                 "<object class=\"GtkListBoxRow\">"
                                                 "<child>"
                                                 "<object class=\"GtkBox\">"
                                                 "<child>"
                                                 "<object class=\"GtkLabel\" id=\"lblImpresionPrueba1\">"
                                                 "<property name=\"halign\">1</property>"
                                                 "<property name=\"hexpand\">true</property>"
                                                 "<property name=\"label\">Impresion de Prueba</property>"
                                                 "<property name=\"valign\">3</property>"
                                                 "<property name=\"xalign\">0</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "<child>"
                                                 "<object class=\"GtkImage\">"
                                                 "<property name=\"halign\">2</property>"
                                                 "<property name=\"icon-name\">printer-symbolic</property>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<style>"
                                                 "<class name=\"rich-list\"/>"
                                                 "<class name=\"boxed-list\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "<style>"
                                                 "<class name=\"tab\"/>"
                                                 "</style>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</child>"
                                                 "</object>"
                                                 "</interface>")
{
    auto builder = Gtk::Builder::create_from_string(XML);
    this->boxConfigImpresora = builder->get_widget<Gtk::Box>("boxConfigImpresora");
    set_margin(10);
    set_homogeneous();
    this->append(*boxConfigImpresora);
}

ViewImpresoras::~ViewImpresoras()
{
}
