#include "tres_filas.hpp"

TresFilas::TresFilas(/* args */) : XML("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                                       "<interface>"
                                       "<requires lib=\"gtk\" version=\"4.0\"/>"
                                       "<object class=\"GtkBox\" id=\"boxCompSuperior\">"
                                       "<property name=\"halign\">3</property>"
                                       "<property name=\"valign\">3</property>"
                                       "<child>"
                                       "<object class=\"GtkFrame\">"
                                       "<child>"
                                       "<object class=\"GtkGrid\">"
                                       "<property name=\"margin-start\">10</property>"
                                       "<property name=\"margin-end\">10</property>"
                                       "<property name=\"margin-top\">10</property>"
                                       "<property name=\"margin-bottom\">10</property>"
                                       "<property name=\"row-spacing\">10</property>"
                                       "<property name=\"column-spacing\">10</property>"
                                       "<child>"
                                       "<object class=\"GtkLabel\" id=\"lblColum1\">"
                                       "<property name=\"label\" translatable=\"true\">Fila 1</property>"
                                       "<property name=\"margin-bottom\">12</property>"
                                       "<layout>"
                                       "<property name=\"row\">0</property>"
                                       "<property name=\"column\">0</property>"
                                       "</layout>"
                                       "</object>"
                                       "</child>"
                                       "<child>"
                                       "<object class=\"GtkEntry\" id=\"etyColum1\">"
                                       "<property name=\"editable\">false</property>"
                                       "<layout>"
                                       "<property name=\"row\">1</property>"
                                       "<property name=\"column\">0</property>"
                                       "</layout>"
                                       "<style>"
                                       "<class name=\"title-4\"/>"
                                       "</style>"
                                       "</object>"
                                       "</child>"
                                       "<child>"
                                       "<object class=\"GtkLabel\" id=\"lblColum2\">"
                                       "<property name=\"label\" translatable=\"true\">Fila 2</property>"
                                       "<property name=\"margin-bottom\">12</property>"
                                       "<layout>"
                                       "<property name=\"row\">0</property>"
                                       "<property name=\"column\">1</property>"
                                       "</layout>"
                                       "</object>"
                                       "</child>"
                                       "<child>"
                                       "<object class=\"GtkEntry\" id=\"etyColum2\">"
                                       "<property name=\"editable\">false</property>"
                                       "<layout>"
                                       "<property name=\"row\">1</property>"
                                       "<property name=\"column\">1</property>"
                                       "</layout>"
                                       "<style>"
                                       "<class name=\"title-4\"/>"
                                       "</style>"
                                       "</object>"
                                       "</child>"
                                       "<child>"
                                       "<object class=\"GtkLabel\" id=\"lblColum3\">"
                                       "<property name=\"label\" translatable=\"true\">Fila 3</property>"
                                       "<property name=\"margin-bottom\">12</property>"
                                       "<layout>"
                                       "<property name=\"row\">0</property>"
                                       "<property name=\"column\">2</property>"
                                       "</layout>"
                                       "</object>"
                                       "</child>"
                                       "<child>"
                                       "<object class=\"GtkEntry\" id=\"etyColum3\">"
                                       "<layout>"
                                       "<property name=\"row\">1</property>"
                                       "<property name=\"column\">2</property>"
                                       "</layout>"
                                       "<style>"
                                       "<class name=\"title-4\"/>"
                                       "</style>"
                                       "</object>"
                                       "</child>"
                                       "<style>"
                                       "<class name=\"title-1\"/>"
                                       "</style>"
                                       "</object>"
                                       "</child>"
                                       "</object>"
                                       "</child>"
                                       "</object>"
                                       "</interface>")
{
    auto builder = Gtk::Builder::create_from_string(XML);

    lblColum1 = builder->get_widget<Gtk::Label>("lblColum1");
    lblColum2 = builder->get_widget<Gtk::Label>("lblColum2");
    lblColum3 = builder->get_widget<Gtk::Label>("lblColum3");

    etyColum1 = builder->get_widget<Gtk::Entry>("etyColum1");
    etyColum2 = builder->get_widget<Gtk::Entry>("etyColum2");
    etyColum3 = builder->get_widget<Gtk::Entry>("etyColum3");

    boxCompSuperior = builder->get_widget<Gtk::Box>("boxCompSuperior");
    append(*boxCompSuperior);
}

TresFilas::~TresFilas()
{
}
