#include "consulta_efectivo.hpp"

ViewEfectivo::ViewEfectivo() : XML(
                                   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
                                   "<interface>\n"
                                   "<requires lib=\"gtk\" version=\"4.0\"/>\n"
                                   "<object class=\"GtkBox\" id=\"box_page_7\">\n"
                                   "<property name=\"halign\">3</property>\n"
                                   "<property name=\"orientation\">1</property>\n"
                                   "<property name=\"spacing\">10</property>\n"
                                   "<property name=\"homogeneous\">false</property>\n"
                                   "<property name=\"margin-bottom\">10</property>\n"
                                   "<property name=\"margin-start\">10</property>\n"
                                   "<property name=\"margin-end\">10</property>\n"
                                   "<property name=\"margin-top\">10</property>\n"
                                   "<child>\n"
                                   "<object class=\"GtkFrame\">\n"
                                   "<property name=\"label\">Billetes</property>\n"
                                   "<child>\n"
                                   "<object class=\"GtkGrid\">\n"
                                   "<property name=\"vexpand\">false</property>\n"
                                   "<property name=\"column-homogeneous\">false</property>\n"
                                   "<property name=\"column-spacing\">38</property>\n"
                                   "<property name=\"row-spacing\">2</property>\n"
                                   "<property name=\"halign\">0</property>\n"
                                   "<property name=\"margin-bottom\">10</property>\n"
                                   "<property name=\"margin-start\">10</property>\n"
                                   "<property name=\"margin-end\">10</property>\n"
                                   "<property name=\"margin-top\">10</property>\n"
                                   "<style>\n"
                                   "<class name=\"title-2\"/>\n"
                                   "</style>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">#</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">0</property>\n"
                                   "</layout>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">   Cantidad Almacenada</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">1</property>\n"
                                   "<property name=\"row\">0</property>\n"
                                   "</layout>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">   CantidadReciclador</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">2</property>\n"
                                   "<property name=\"row\">0</property>\n"
                                   "</layout>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$20</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">1</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$50</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">2</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$100</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">3</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$200</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">4</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$500</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">5</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$1000</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">6</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">Total</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">7</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-3\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillRecy0\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">1</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillRecy1\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">2</property>\n"
                                   "<property name=\"row\">2</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillRecy2\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">3</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillRecy3\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">4</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillRecy4\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">5</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillRecy5\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">6</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillRecy6\">\n"
                                   "<property name=\"label\">6</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">7</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-3\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillCant0\">\n"
                                   "<property name=\"label\">1</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">1</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillCant1\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">1</property>\n"
                                   "<property name=\"row\">2</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillCant2\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">3</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillCant3\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">4</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillCant4\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">5</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillCant5\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">6</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblBillCant6\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">7</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-3\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkFrame\">\n"
                                   "<property name=\"label\">Monedas</property>\n"
                                   "<child>\n"
                                   "<object class=\"GtkGrid\">\n"
                                   "<property name=\"vexpand\">false</property>\n"
                                   "<property name=\"hexpand\">false</property>\n"
                                   "<property name=\"column-homogeneous\">false</property>\n"
                                   "<property name=\"column-spacing\">38</property>\n"
                                   "<property name=\"row-spacing\">2</property>\n"
                                   "<property name=\"halign\">0</property>\n"
                                   "<property name=\"margin-bottom\">10</property>\n"
                                   "<property name=\"margin-start\">10</property>\n"
                                   "<property name=\"margin-end\">10</property>\n"
                                   "<property name=\"margin-top\">10</property>\n"
                                   "<style>\n"
                                   "<class name=\"title-2\"/>\n"
                                   "</style>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">#</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">0</property>\n"
                                   "</layout>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">   Cantidad Almacenada</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">1</property>\n"
                                   "<property name=\"row\">0</property>\n"
                                   "</layout>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">   CantidadReciclador</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">2</property>\n"
                                   "<property name=\"row\">0</property>\n"
                                   "</layout>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$1</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">1</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$2</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">2</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$5</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">3</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">$10</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">4</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\">\n"
                                   "<property name=\"label\">Total</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">0</property>\n"
                                   "<property name=\"row\">5</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-3\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinRecy0\">\n"
                                   "<property name=\"label\">1</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">1</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinRecy1\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">2</property>\n"
                                   "<property name=\"row\">2</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinRecy2\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">3</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinRecy3\">\n"
                                   "<property name=\"label\">3</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">4</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinRecy4\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">02</property>\n"
                                   "<property name=\"row\">5</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-3\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinCant0\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">1</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinCant1\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">1</property>\n"
                                   "<property name=\"row\">2</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinCant2\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">3</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinCant3\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">4</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-4\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "<child>\n"
                                   "<object class=\"GtkLabel\" id=\"lblCoinCant4\">\n"
                                   "<property name=\"label\">0</property>\n"
                                   "<layout>\n"
                                   "<property name=\"column\">01</property>\n"
                                   "<property name=\"row\">5</property>\n"
                                   "</layout>\n"
                                   "<style>\n"
                                   "<class name=\"title-3\"/>\n"
                                   "</style>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "</object>\n"
                                   "</child>\n"
                                   "</object>"
                                   "</interface>")
{
  auto builder = Gtk::Builder::create_from_string(XML);
  this->boxVistaEfectivo = builder->get_widget<Gtk::Box>("boxVistaEfectivo");

  this->colViewRecicladorBilletes = builder->get_widget<Gtk::ColumnView>("colViewRecicladorBilletes");
  this->colViewRecicladorMonedas = builder->get_widget<Gtk::ColumnView>("colViewRecicladorMonedas");

  this->lblTotalMXN1 = builder->get_widget<Gtk::Label>("lblTotalMXN1");
  this->lblTotalMXN2 = builder->get_widget<Gtk::Label>("lblTotalMXN2");
  this->lblTotalMXN3 = builder->get_widget<Gtk::Label>("lblTotalMXN3");
  this->lblTotalMXN4 = builder->get_widget<Gtk::Label>("lblTotalMXN4");
  this->lblTotalMXN5 = builder->get_widget<Gtk::Label>("lblTotalMXN5");

  this->lblTotalNum1 = builder->get_widget<Gtk::Label>("lblTotalNum1");
  this->lblTotalNum2 = builder->get_widget<Gtk::Label>("lblTotalNum2");

  this->lblTotalCasette = builder->get_widget<Gtk::Label>("lblTotalCasette");

  this->boxVistaEfectivo->set_margin(10);
  this->append(*boxVistaEfectivo);
}

ViewEfectivo::~ViewEfectivo()
{
}