#include "consultaEfectivo.hpp"

ViewEfectivo::ViewEfectivo() : XML("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                                   "<interface>"
                                   "<requires lib=\"gtk\" version=\"4.0/\>"
                                   "<object class=\"GtkBox\" id=\"boxVistaEfectivo\">"
                                   "<property name=\"spacing\">20</property>"
                                   "<property name=\"halign\">3</property>"
                                   "<property name=\"valign\">3</property>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"orientation\">1</property>"
                                   "<property name=\"spacing\">20</property>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmRecicladorMonedas\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12</property>"
                                   "<property name=\"margin-end\">12</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Reciclador de Monedas</property>"
                                   "<style>"
                                   "<class name=\"title-1\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkColumnView\" id=\"colViewRecicladorMonedas\">"
                                   "<property name=\"hexpand\">true</property>"
                                   "</object>"
                                   "</child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"halign\">2</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalMXN1\">"
                                   "<property name=\"label\">0.00 MXN</property>"
                                   "<style>"
                                   "<class name=\"title-4\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalNum1\">"
                                   "<property name=\"label\">Total</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">100</property>"
                                   "<style>"
                                   "<class name=\"title-4\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmRecicladorBilletes\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12</property>"
                                   "<property name=\"margin-end\">12</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Reciclador de Billetes</property>"
                                   "<style>"
                                   "<class name=\"title-1\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-top\">12</property>"
                                   "<property name=\"margin-bottom\">12</property>"
                                   "<property name=\"spacing\">10</property>"
                                   "<child>"
                                   "<object class=\"GtkColumnView\" id=\"colViewRecicladorBilletes\">"
                                   "<property name=\"hexpand\">true</property>"
                                   "</object>"
                                   "</child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"halign\">2</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalMXN2\">"
                                   "<property name=\"label\">0.00 MXN</property>"
                                   "<style>"
                                   "<class name=\"title-4\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalNum2\">"
                                   "<property name=\"label\">Total</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">100</property>"
                                   "<style>"
                                   "<class name=\"title-4\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"spacing\">20</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmTotal\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12</property>"
                                   "<property name=\"margin-end\">12</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total</property>"
                                   "<style>"
                                   "<class name=\"title-1\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalMXN3\">"
                                   "<property name=\"label\">8,410.00 MXN</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmTotal2\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12</property>"
                                   "<property name=\"margin-end\">12</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total</property>"
                                   "<style>"
                                   "<class name=\"title-1\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalMXN4\">"
                                   "<property name=\"label\">8,410.00 MXN</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmTotal3\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12</property>"
                                   "<property name=\"margin-end\">12</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total</property>"
                                   "<style>"
                                   "<class name=\"title-1\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalMXN5\">"
                                   "<property name=\"label\">8,410.00 MXN</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmCasetteBilletes\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12</property>"
                                   "<property name=\"margin-end\">12</property>"
                                   "<property name=\"orientation\">1</property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Casette de Billetes</property>"
                                   "<style>"
                                   "<class name=\"title-1\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object class=\"GtkLabel\" id=\"lblTotalCasette\">"
                                   "<property name=\"label\">8,410.00 MXN</property>"
                                   "<style>"
                                   "<class name=\"title-2\">"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<interface>")
{
    auto builder = Gtk::Builder::create_from_string(XML);
    this->boxVistaEfectivo = builder->get_widget<Gtk::Box>("boxVistaEfectivo");
    this->lblTotalMXN1 = builder->get_widget<Gtk::Label>("lblTotalMXN1");    
    this->lblTotalMXN2 = builder->get_widget<Gtk::Label>("lblTotalMXN2");
    this->lblTotalMXN3 = builder->get_widget<Gtk::Label>("lblTotalMXN3");
    this->lblTotalMXN4 = builder->get_widget<Gtk::Label>("lblTotalMXN4");
    this->lblTotalMXN5 = builder->get_widget<Gtk::Label>("lblTotalMXN5");

    this->lblTotalNum1 = builder->get_widget<Gtk::Label>("lblTotalNum1");
    this->lblTotalNum2 = builder->get_widget<Gtk::Label>("lblTotalNum2");

    this->lblTotalCasette = builder->get_widget<Gtk::Label>("lblTotalCasette");

    this->boxVistaEfectivo->set_margin(10);
    this->append(*boxVistaEfectivo);
}

ViewEfectivo::~ViewEfectivo()
{
}