#include "consultaEfectivo.hpp"

ViewEfectivo::ViewEfectivo() : XML("<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                                   "<interface>"
                                   "<requires lib=\"gtk\" version=\"4.0\"\>"
                                   "<object class=\"GtkBox\" id=\"boxVistaEfectivo\">"
                                   "<property name=\"spacing\">20<property>"
                                   "<property name=\"halign\">3<property>"
                                   "<property name=\"valign\">3<property>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"orientation\">1<property>"
                                   "<property name=\"spacing\">20<property>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmRecicladorMonedas\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12<property>"
                                   "<property name=\"margin-end\">12<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Reciclador de Monedas<property>"
                                   "<style>"
                                   "<class name=\"title-1\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"halign\">2<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">0.00 MXN<property>"
                                   "<style>"
                                   "<class name=\"title-4\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">100<property>"
                                   "<style>"
                                   "<class name=\"title-4\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmRecicladorBilletes\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12<property>"
                                   "<property name=\"margin-end\">12<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Reciclador de Billetes<property>"
                                   "<style>"
                                   "<class name=\"title-1\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-top\">12<property>"
                                   "<property name=\"margin-bottom\">12<property>"
                                   "<property name=\"spacing\">10<property>"
                                   "<child>"
                                   "<object class=\"GtkTreeView\" id=\"treeRecicladorBilletes\">"
                                   "<property name=\"hexpand\">true<property>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"halign\">2<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">0.00 MXN<property>"
                                   "<style>"
                                   "<class name=\"title-4\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">100<property>"
                                   "<style>"
                                   "<class name=\"title-4\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"spacing\">20<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmTotal\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12<property>"
                                   "<property name=\"margin-end\">12<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total<property>"
                                   "<style>"
                                   "<class name=\"title-1\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">8,410.00 MXN<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmTotal2\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12<property>"
                                   "<property name=\"margin-end\">12<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total<property>"
                                   "<style>"
                                   "<class name=\"title-1\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">8,410.00 MXN<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmTotal3\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12<property>"
                                   "<property name=\"margin-end\">12<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Total<property>"
                                   "<style>"
                                   "<class name=\"title-1\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">8,410.00 MXN<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkFrame\" id=\"frmCasetteBilletes\">"
                                   "<child>"
                                   "<object class=\"GtkBox\">"
                                   "<property name=\"margin-start\">12<property>"
                                   "<property name=\"margin-end\">12<property>"
                                   "<property name=\"orientation\">1<property>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">Casette de Billetes<property>"
                                   "<style>"
                                   "<class name=\"title-1\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<child>"
                                   "<object class=\"GtkLabel\">"
                                   "<property name=\"label\">8,410.00 MXN<property>"
                                   "<style>"
                                   "<class name=\"title-2\"\>"
                                   "<style>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<child>"
                                   "<object>"
                                   "<interface>")
{
    auto builder = Gtk::Builder::create_from_string(XML);
    this->boxVistaEfectivo = builder->get_widget<Gtk::Box>("boxVistaEfectivo");
    this->frmRecicladorMonedas = builder->get_widget<Gtk::Frame>("frmRecicladorMonedas");
    this->frmRecicladorBilletes = builder->get_widget<Gtk::Frame>("frmRecicladorBilletes");
    this->treeRecicladorBilletes= builder->get_widget<Gtk::TreeView>("treeRecicladorBilletes");
    this->frmTotal = builder->get_widget<Gtk::Frame>("frmTotal");
    this->frmTotal2 = builder->get_widget<Gtk::Frame>("frmTotal2");
    this->frmTotal3 = builder->get_widget<Gtk::Frame>("frmTotal3");
    this->frmCasetteBilletes = builder->get_widget<Gtk::Frame>("frmCasetteBilletes");
    
    this->boxVistaEfectivo->set_margin(10);
    this->append(*boxVistaEfectivo);
}

ViewEfectivo::~ViewEfectivo()
{
}